lab_1/urls.py
from django.urls import path
from .views import home, index
#url for app
urlpatterns = [
    path('', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path, path
from django.contrib import admin
from lab_1.views import home

urlpatterns = [
    path('', home, name="index-home"),

    path('account/', include(('account.urls', 'account'), namespace="account")),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here

    path('admin/', admin.site.urls),

    path('lab-1/', include(('lab_1.urls', 'lab_1'), namespace="lab-1")),
    path('lab-2/', include(('lab_2.urls', 'lab_2'), namespace="lab-2")),

    path('lab-3/', include(('lab_3.urls', 'lab_3'), namespace="lab-3")),
    path('lab-4/', include('lab_3.urls')),

    path('story-6/', include(('story_6.urls', 'story_6'), namespace="story-6")),
    path('story-7/', include('story_6.urls')),

    path('story-8/', include(('story_8.urls', 'story_8'), namespace="story-8")),
    path('story-9/', include(('story_9.urls', 'story_9'), namespace="story-9")),

    path('story-10/', include(('story_10.urls', 'story_10'), namespace="story-10")),

    path('jadwal/', include('jadwal.urls')),


]

story_9/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (index,
                    add_to_favorite,
                    remove_from_favorite,
                    index_partial,
                    get_book_json,
                    get_fav_counter)

urlpatterns = [
    path('', index, name='index'),
    path('get-book-json/', get_book_json, name='get-book-json'),
    path('get-fav-counter/', get_fav_counter, name='get-fav-counter'),
    path('partial/', index_partial, name='index-partial'),
    path('add-to-favorite/', add_to_favorite, name='add-to-favorite'),
    path('remove-from-favorite/', remove_from_favorite, name='remove-from-favorite'),
]

story_9/models.py
from django.db import models

# Create your models here.
class Favorited(models.Model):
    book_id = models.CharField(primary_key=True, max_length=200)

story_9/views.py
import requests
import json
from django.shortcuts import render, redirect
from django.http import JsonResponse
# from .api_firer import *
from .models import Favorited
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
#BOOK_API_URL = "https://www.googleapis.com/books/v1/volumes?q=quitling"
#BOOK_LIST =  requests.get(BOOK_API_URL).json()
#BOOK_ID_LIST = [ BOOK_LIST['items'][book]['id'] for book in range(len(BOOK_LIST['items'])) ]

try:
    liked_books = request.session['liked_books']
except:
    liked_books = []


@csrf_exempt
def index(request):
    if(not request.user.is_authenticated):
        return redirect("/")
    response = {}

    if(request.user.is_authenticated):
        if(request.session['firstLogged']):
            liked_books = []
            request.session['liked_books'] = liked_books
            request.session['firstLogged'] = False

    for key, val in request.session.items():
        print("""   ============
        [{}]====[{}]
        ============""".format(key, val))

    # favorited = Favorited.objects.all()
    # favorited_id = [ fav.book_id for fav in favorited ]

    # response = {
    #     "favorited" : favorited_id,
    # }

    return render(request, 'index9.html', response)

def get_book_json(request):
    try:
        q = request.GET['q']
    except:
        q = ""

    BOOK_API_URL = "https://www.googleapis.com/books/v1/volumes?q=" + q
    BOOK_LIST =  requests.get(BOOK_API_URL).json()
    # BOOK_ID_LIST = [ BOOK_LIST['items'][book]['id'] for book in range(len(BOOK_LIST['items'])) ]
    BOOK_LIST['liked_books'] = liked_books
    return JsonResponse(BOOK_LIST)

def get_fav_counter(request):
    favorited = Favorited.objects.all()
    favorited_id = [ fav.book_id for fav in favorited ]
    response = {
        "fav-ids": favorited_id,
        "fav-counts": len(favorited_id),
        "status_code": 200,
    }
    return JsonResponse(response)


# below this used when implementing ajax request and save to database
@csrf_exempt
def index_partial(request):
    response = {}
    favorited = Favorited.objects.all()

    favorited_id = [ fav.book_id for fav in favorited ]

    # from django.conf import settings

    response = {
        "books" : BOOK_LIST,
        "favorited" : favorited_id,
    }

    return render(request, 'index9_partial.html', response)

@csrf_exempt
def add_to_favorite(request):
    if(request.method == "POST"):
        liked_book_id = request.POST['liked']
        if(liked_book_id not in liked_books):
            liked_books.append(liked_book_id)
            request.session['liked_books'] = liked_books

        for key, val in request.session.items():
            print("""   ============
            [{}]====[{}]
            ============""".format(key, val))

        return JsonResponse({"result" : "success", 'status' : 200}, safe=False)
        # return JsonResponse({"result" : "success", 'status' : 403}, safe=False)
    return JsonResponse({"result" : "No Get Method", 'status' : 403}, safe=False)

@csrf_exempt
def remove_from_favorite(request):
    if(request.method == "POST"):
        try:
            liked_book_id = request.POST['liked']
        except:
            return JsonResponse({"result" : "error occured", 'status' : 400}, safe=False)
        if(liked_book_id in liked_books):
            liked_books.remove(liked_book_id)
            request.session['liked_books'] = liked_books
        for key, val in request.session.items():
            print("""   ============
            [{}]====[{}]
            ============""".format(key, val))
        return JsonResponse({"result" : "success", 'status' : 200}, safe=False)
    return JsonResponse({"result" : "No Get Method", 'status' : 403}, safe=False)

story_9/templates/index9.html
{% extends 'main.html' %}

{% load static %}

{% block title %}
Story 9
{% endblock %}

{% block extracss %}
  <link rel="stylesheet" href="{% static 'css/style9.css' %}">
{% endblock %}

{% block content %}

<div id="story-9" class="bg-grey title" style="height:100%;">
  <div id="books-api" class="grid-container f-h">
    <h1 class="title font-kayak">Google Books API</h1>
    <input id="searchbar" type="text" name="" value="" placeholder="Search books..." style="display:inline">
    <h3 class="subtitle" style="display:inline;">Favorited:</h3>
    <h3 id="favorited" style="display:inline" class="subtitle">0</h3>
    <table id="favorited-table" class="bg-grey stack">
      <thead>
        <tr>
          <!-- <th class="subtitle bg-grey">ID</th> -->
          <th class="subtitle bg-grey">Cover</th>
          <th class="subtitle bg-grey">Title</th>
          <th class="subtitle bg-grey">Author</th>
          <th class="subtitle bg-grey">Published Date</th>
          <th class="subtitle bg-grey"></th>
        </tr>
      </thead>
      <tbody id="books-list">
      </tbody>
    </table>
  </div>

  {% block extrajs %}
  <script type="text/javascript">
    var yellow_star = "{% static 'img/icon/kuning.png' %}";
    var blue_star = "{% static 'img/icon/biru.png' %}";
    var story_9_url = "{% url 'story-9:index' %}";
    var story_9_url_partial = "{% url 'story-9:index-partial' %}";
    var add_fav_url = "{% url 'story_9:add-to-favorite' %}";
    var rem_fav_url = "{% url 'story_9:remove-from-favorite' %}";
    var get_book_json_url = "{% url 'story_9:get-book-json' %}";
  </script>
  <script type="text/javascript" src="{% static 'js/google-api-ajax.js' %}"></script>
  <script>
    var username = "{{ user.username }}"
  </script>
  {% endblock %}

  {% endblock %}
</div>

story_9/templates/index9_partial.html
{% load static %}

<div id="books-api" class="grid-container f-h">
<h1 class="title font-kayak">Google Books API</h1>
<h3 class="subtitle" style="display:inline;">Favorited:</h3>
<h3 id="favorited" style="display:inline" class="subtitle">{{ favorited|length }}</h3>
<table class="bg-grey stack">
    <thead>
      <tr>
        <!-- <th class="subtitle bg-grey">ID</th> -->
        <th class="subtitle bg-grey">Title</th>
        <th class="subtitle bg-grey">Author</th>
        <th class="subtitle bg-grey">Published Date</th>
        <th class="subtitle bg-grey"></th>
      </tr>
    </thead>
    <tbody>
        {% for book in books.items %}
            <tr>
                {% if book.id in favorited %}
                    <!-- <td class="text bg-grey">{{ book.id }}</td> -->
                    <td class="text bg-grey">{{ book.volumeInfo.title }}</td>
                    <td class="text bg-grey">{{ book.volumeInfo.authors.0 }}</td>
                    <td class="text bg-grey">{{ book.volumeInfo.publishedDate }}</td>
                    <td class="text bg-grey">
                        <!-- <button class="button alert tiny" onclick="removeFromFavorite('{{book.id}}');">Remove from Facvorite</button> -->
                        <img width="30" src="{% static 'img/icon/kuning.png' %}" alt="" onclick="removeFromFavorite(this, '{{book.id}}');">
                    </td>
                {% else %}
                    <td class="text bg-grey">{{ book.volumeInfo.title }}</td>
                    <td class="text bg-grey">{{ book.volumeInfo.authors.0 }}</td>
                    <td class="text bg-grey">{{ book.volumeInfo.publishedDate }}</td>
                    <td class="text bg-grey">
                        <!-- <button class="button tiny" onclick="addToFavorite('{{book.id}}');">Add to Favorite</button> -->
                        <img width="30" src="{% static 'img/icon/biru.png' %}" alt="" onclick="addToFavorite(this, '{{book.id}}');">
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
  </table>
</div>