account/urls.py
from django.conf.urls import include
from django.urls import re_path, path
from django.contrib import admin
from .views import login, logout
from django.contrib import auth

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

lab_1/urls.py
from django.urls import path
from .views import home, index
#url for app
urlpatterns = [
    path('', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path, path
from django.contrib import admin
from lab_1.views import home

urlpatterns = [
    path('', home, name="index-home"),

    path('account/', include(('account.urls', 'account'), namespace="account")),
    path('auth/', include('social_django.urls', namespace='social')),  # <- Here

    path('admin/', admin.site.urls),

    path('lab-1/', include(('lab_1.urls', 'lab_1'), namespace="lab-1")),
    path('lab-2/', include(('lab_2.urls', 'lab_2'), namespace="lab-2")),

    path('lab-3/', include(('lab_3.urls', 'lab_3'), namespace="lab-3")),
    path('lab-4/', include('lab_3.urls')),

    path('story-6/', include(('story_6.urls', 'story_6'), namespace="story-6")),
    path('story-7/', include('story_6.urls')),

    path('story-8/', include(('story_8.urls', 'story_8'), namespace="story-8")),
    path('story-9/', include(('story_9.urls', 'story_9'), namespace="story-9")),

    path('story-10/', include(('story_10.urls', 'story_10'), namespace="story-10")),

    path('jadwal/', include('jadwal.urls')),


]

lab_1/models.py
from django.db import models

# Create your models here.

lab_1/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime, date
import json
# Enter your name here
mhs_name = 'Fachry Nataprawira'
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1998, 9, 15) #TODO Implement this, format (Year, Month, Date)
npm = 1706039703 # TODO Implement this
# Create your views here.

def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def home(request):
    # return HttpResponse("Hello")
    if(request.user.is_authenticated):
            try:
                request.session['firstLogged']
            except:
                request.session['firstLogged'] = True
                request.session['full_name'] = "{} {}".format(request.user.first_name, request.user.last_name)
                request.session['username'] = request.user.username

    for key, val in request.session.items():
        print("""   ============
        [{}]====[{}]
        ============""".format(key, val))

    return render(request, 'home.html', {})

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_1/templates/home.html
{% extends 'main.html' %}

{% load static %}

{% block title %}
  Daftar Isi
{% endblock %}

{% block extracss %}

{% endblock %}

{% block content %}

<div id="home" class="bg-grey title" style="height:100%;">
  <div class="grid-container">
    <div class="grid-x align-center align-middle f-h">
      <div class="small-12 cell">
        <div class="grid-x align-middle f-h">
          <div class="small-12">

            {% if user.is_authenticated %}
               <p class="display-4">Hello, {{ user.username }}</p>
               <a class="lead" href="{% url 'account:logout' %}">Log out</a>
          	{% else %}
                <h3 class="title">Login dulu breeeeee</h3>
                <a class="lead" href="{% url 'account:login' %}">Log in</a>
          	{% endif %}

            <h1 class="title"> Daftar Isi</h1>
            <div id="list-of-story">
              <ul>
                <li>
                  <a href="{% url 'lab-1:index' %}">Story-1 (Intro to WebPro)</a>
                  <small class="subtext">Bikin web tapi ga pake framework django</small>
                </li>
                <li>
                  <a href="#">Story-2 (Designing your own website + Intro to HTML5)</a>
                  <small class="subtext">Ini ga ngoding tapi bikin design</small>
                </li>
                <li>
                  <a href="{% url 'lab-3:index' %}">Story-3 (HTML5, CSS, and Responsive Design File) </a>
                  <small class="subtext">Implementasi design story-2 pake css framework (improve story-1)</small>
                </li>
                <li>
                  <a href="{% url 'lab-3:index' %}">Story-4 (Intro to Django Framework File)</a>
                  <small class="subtext">Deploy app terus pake django masih improve story-1</small>
                </li>
                <li>
                  <a href="{% url 'story-6:index' %}">Story-5 (Django Framework (Models) File)</a>
                  <small class="subtext">Ini udah buat models</small>
                </li>
                <li>
                  <a href="{% url 'story-6:index' %}">Story-6 (TDD with Django)</a>
                  <small class="subtext">Improvement dari story-5, nambahin test</small>
                </li>
                <li>
                  <a href="{% url 'story-6:index' %}">Story-7 (Unit & Functional Test URL)</a>
                  <small class="subtext">Improvement dari story-6, nambahin funtional test pake selenium</small>
                </li>
                <li>
                  <a href="{% url 'story-8:index' %}">Story-8 (Java Script & JQuery URL)</a>
                  <small class="subtext">Coba-coba javascript & jquery (bikin accordion dan switch theme)</small>
                </li>
                <li>
                  <a href="{% url 'story-9:index' %}">Story-9 (AJAX Dynamic Data Access URL)</a>
                  <small class="subtext">Coba request menggunakan ajax</small>
                </li>
                <li>
                  <a href="{% url 'story-10:index' %}">Story-10 (Webservice)</a>
                  <small class="subtext">Bikin webservice sederhana(subscribe newsletter)</small>
                </li>
                <li>
                  <a href="{% url 'story-9:index' %}">Story-11 (Oauth, Session, Cookies)</a>
                  <small class="subtext">Lanjutan dr story 9</small>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}
</div>

lab_1/templates/index_lab1.html
{% extends 'main.html' %}

{% load static %}

{% block extracss %}
{% endblock %}

{% block content %}
<div id="home" class="bg-light-violet">
  <div class="grid-container">

      <div class="grid-x align-center align-middle text-center f-h" >
        <div class="small-12 medium-4 text-center">
          <img class="" src="{% static "img/polar-me.png" %}" style="max-width :200px;" alt="My image">
        </div>
        <div class="small-12 small-only-text-center medium-8 medium-text-left">
          <h1 class="blue font-kayak">Hello my name is {{ name }}</h1>
          <article class="subtitle font-kayak">NPM : {{ npm }}</article>
          <article class="subtitle font-kayak">I am {{ age }} years old</article>
          <p class="yellow font-kayak">
            aku adalah anak gembala selalu riang serta gembira
          </p>
          <a href="http://instagram.com/nataprawiraf"><img src="{% static "img/icon/instagram.svg" %}" alt=""></a>
          <a href="http://twitter.com/nataprawiraf"><img src="{% static "img/icon/twitter.svg" %}" alt=""></a>
        </div>
      </div>

      <div class="grid-x align-center align-middle text-center f-h" >
        <div class="small-12 medium-4 text-center">
          <img class="" src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/19510520_1722156197814013_1997303375033274909_n.jpg?_nc_cat=0&oh=a2958304cc54c81457e820d81ccc55f8&oe=5C349E24" style="max-width :200px;" alt="My image">
        </div>
        <div class="small-12 small-only-text-center medium-8 medium-text-left">
          <h1 class="blue font-kayak">He is Irfan, he sat in front of me when doing ppw challange</h1>
          <article class="subtitle font-kayak">NPM : 1706039585</article>
          <article class="subtitle font-kayak">he is 19 years old</article>
          <p class="yellow font-kayak">
            He is completely a weaboo.
            He realy likes photography and he is Vice Project Officer of BETIS.
          </p>
          <a href="http://instagram.com/irfanamrl"><img src="{% static "img/icon/instagram.svg" %}" alt=""></a>
        </div>
      </div>

      <div class="grid-x align-center align-middle text-center f-h" >
        <div class="small-12 medium-4 text-center">
        </div>
        <div class="small-12 small-only-text-center medium-8 medium-text-left">
          <h1 class="blue font-kayak">There is Haidar, he sat behind me when doing ppw challange</h1>
          <article class="subtitle font-kayak">NPM : 1406558216</article>
          <article class="subtitle font-kayak">he is 22 years old</article>
          <p class="yellow font-kayak">
            He is from math departement and he took PPW class the same class as me.
            I wish I could get his pic and instagram acc:(
          </p>
        </div>
      </div>
    </div>
  </div>

{% endblock %}